apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mqtt-persistent-data-{{ default "staging" .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 4Gi
---
