apiVersion: v1
kind: Service
metadata:
  name: mqtt-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
  labels:
    tier: backend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dns.hostname }}{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.{{ .Values.dns.name }}
    service.beta.kubernetes.io/azure-dns-label-name: calvincs-mqtt{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}
spec:
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
    protocol: TCP
  - port: 8883
    targetPort: 8883
    name: mqtttls
    protocol: TCP
  - port: 8080
    targetPort: 8080
    name: mqttwebsockets
    protocol: TCP
  - port: 8083
    targetPort: 8083
    name: mqttwebsocketstls
    protocol: TCP
  selector:
    app: mqtt-{{ default "staging" .Release.Namespace }}
